import AppKit
import Defaults
import Foundation
import Logging
import Testing
@testable import ClipKit

extension ClipKitGlobalStateTests {
    /// Each test writes something that must be skipped, then a plain copy that must be recorded,
    /// so none can pass just because recording is broken.
    @Suite
    @MainActor
    struct NeverRecordedTests {
        @Test func concealedTypesNeverRecorded() {
            expectSkipped { scratch in
                scratch.write(string: "concealed-secret", markedAs: [.concealed])
            }
            expectSkipped { scratch in
                scratch.write(string: "onepassword-secret", markedAs: [NSPasteboard.PasteboardType("com.agilebits.onepassword")])
            }
        }

        @Test func transientAndAutoGeneratedNeverRecorded() {
            expectSkipped { scratch in
                scratch.write(string: "transient-secret", markedAs: [.transient])
            }
            expectSkipped { scratch in
                scratch.write(string: "generated-secret", markedAs: [.autoGenerated])
            }
        }

        @Test func concealedMarkerOnImageNeverRecorded() throws {
            let image = try #require(NSImage(named: NSImage.infoName)?.tiffRepresentation)
            expectSkipped { scratch in
                scratch.write([.tiff: image, .concealed: Data()])
            }
            expectSkipped { scratch in
                scratch.write([.fileURL: Data("file:///tmp/secret.txt".utf8), .concealed: Data()])
            }
            // The marker on a second pasteboard item still covers the first.
            expectSkipped { scratch in
                let picture = NSPasteboardItem()
                picture.setData(image, forType: .tiff)
                let marker = NSPasteboardItem()
                marker.setData(Data(), forType: .concealed)
                scratch.pasteboard.clearContents()
                scratch.pasteboard.writeObjects([picture, marker])
            }
        }

        @Test func ignoredAppNeverRecorded() {
            Fixture.resetSettings()
            let passwordManagers = [
                "com.agilebits.onepassword7", "com.1password.1password", "com.bitwarden.desktop",
                "com.dashlane.dashlanephonefinal", "com.lastpass.LastPass", "org.keepassxc.keepassxc",
                "com.apple.keychainaccess", "com.apple.Passwords"
            ]
            #expect(Set(ClipKit.settingsValues().ignoredApps).isSuperset(of: passwordManagers))

            expectSkipped(sourceApp: "com.1password.1password") { scratch in
                scratch.write(string: "from-1password")
            }
        }

        @Test func secureInputBlocksRecording() {
            var secureInput = true
            expectSkipped(secureInput: { secureInput }, before: { secureInput = false }, { scratch in
                scratch.write(string: "typed-in-secure-field")
            })
        }

        @Test func universalClipboardOffByDefault() {
            Fixture.resetSettings()
            #expect(!ClipKit.settingsValues().recordUniversalClipboard)

            let remote = NSPasteboard.PasteboardType("com.apple.is-remote-clipboard")
            expectSkipped { scratch in
                scratch.write(string: "from-iphone", markedAs: [remote])
            }

            let scratch = TestPasteboard()
            defer { scratch.release() }
            let kit = Fixture.kit(pasteboard: scratch)
            Fixture.start(kit)
            defer { kit.stop() }
            var values = ClipKit.settingsValues()
            values.recordUniversalClipboard = true
            ClipKit.setSettingsValues(values)
            scratch.write(string: "from-iphone-allowed", markedAs: [remote])
            Fixture.poll()
            #expect(Fixture.recordedTitles() == ["from-iphone-allowed"])
        }

        @Test func historySizeDefault200() {
            Fixture.resetSettings()
            #expect(Defaults.Keys.size.defaultValue == 200)
            #expect(ClipKit.settingsValues().historySize == 200)
            #expect(!ClipKit.settingsValues().clearOnQuit)
        }

        @Test func noContentInLogs() throws {
            let captured = LogCapture()
            let saved = ClipKitLog.logger
            ClipKitLog.logger = Logger(label: "dev.mooring.clipkit.tests") { _ in CapturingLogHandler(capture: captured) }
            defer { ClipKitLog.logger = saved }

            let scratch = TestPasteboard()
            defer { scratch.release() }
            let kit = Fixture.kit(pasteboard: scratch)
            Fixture.start(kit)
            defer { kit.stop() }

            let secret = "hunter2-correct-horse-battery-staple"
            scratch.write(string: secret)
            Fixture.poll()
            scratch.write(string: secret) // a duplicate takes Maccy's "Removing duplicate" path
            Fixture.poll()
            let recorded = try #require(kit.recent(limit: 1).first)
            #expect(recorded.title == secret)
            kit.copy(recorded.id)
            kit.clear(all: false)
            kit.clear(all: true)

            #expect(!captured.lines.isEmpty, "the capture saw nothing, so it proves nothing")
            #expect(!captured.lines.contains { $0.contains(secret) || $0.contains("hunter2") })
        }

        @Test func pasteWithoutAccessibilityOnlyCopies() throws {
            let scratch = TestPasteboard()
            defer { scratch.release() }
            var trustChecks = 0
            let kit = Fixture.kit(pasteboard: scratch, trusted: {
                trustChecks += 1
                return false
            })
            Fixture.start(kit)
            defer { kit.stop() }

            scratch.write(string: "paste-me")
            Fixture.poll()
            let item = try #require(kit.recent(limit: 1).first)
            scratch.pasteboard.clearContents()

            kit.paste(item.id, plain: true)
            #expect(scratch.pasteboard.string(forType: .string) == "paste-me")
            #expect(trustChecks > 0)
        }

        /// Writes the skipped fixture, polls, and expects nothing recorded; then a plain copy, which is.
        private func expectSkipped(
            sourceApp: String? = nil,
            secureInput: @escaping () -> Bool = { false },
            before: () -> Void = {},
            _ writeSkipped: (TestPasteboard) -> Void,
            sourceLocation: SourceLocation = #_sourceLocation
        ) {
            let scratch = TestPasteboard()
            defer { scratch.release() }
            var currentApp = sourceApp
            let kit = Fixture.kit(pasteboard: scratch, sourceApp: { currentApp }, secureInput: secureInput)
            Fixture.start(kit)
            defer { kit.stop() }

            writeSkipped(scratch)
            Fixture.poll()
            #expect(Fixture.recordedTitles().isEmpty, sourceLocation: sourceLocation)

            before()
            currentApp = "com.apple.TextEdit"
            scratch.write(string: "control-copy")
            Fixture.poll()
            #expect(Fixture.recordedTitles() == ["control-copy"], sourceLocation: sourceLocation)
        }
    }
}

final class LogCapture: @unchecked Sendable {
    private let lock = NSLock()
    private var stored: [String] = []

    var lines: [String] { lock.withLock { stored } }

    func append(_ line: String) {
        lock.withLock { stored.append(line) }
    }
}

struct CapturingLogHandler: LogHandler {
    let capture: LogCapture
    var metadata: Logger.Metadata = [:]
    var logLevel: Logger.Level = .trace

    subscript(metadataKey key: String) -> Logger.Metadata.Value? {
        get { metadata[key] }
        set { metadata[key] = newValue }
    }

    // swiftlint:disable:next function_parameter_count
    func log(
        level: Logger.Level,
        message: Logger.Message,
        metadata: Logger.Metadata?,
        source: String,
        file: String,
        function: String,
        line: UInt
    ) {
        let merged = self.metadata.merging(metadata ?? [:]) { _, new in new }
        capture.append("\(level) \(message) \(merged)")
    }
}
