import CoreGraphics

/// The frame maths of Loop's "next/previous screen" (from `LoopManager.changeAction`), with the
/// screens passed in so it can be tested without real displays.
enum ScreenSwitchFrames {
    static let autogeneratedName = "autogenerated_screen_switching_action"

    /// A custom action that keeps the window's frame in proportion to `bounds`, as Loop builds it.
    static func proportionalAction(window: CGRect, bounds: CGRect) -> WindowAction {
        WindowAction(
            .custom,
            keybind: [],
            name: autogeneratedName,
            unit: .percentage,
            width: window.width / bounds.width * 100,
            height: window.height / bounds.height * 100,
            xPoint: (window.minX - bounds.minX) / bounds.width * 100,
            yPoint: (window.minY - bounds.minY) / bounds.height * 100,
            positionMode: .coordinates,
            sizeMode: .custom
        )
    }

    /// Where a window on `screen` lands after `direction` (next or previous screen) among `screens`.
    static func frame(for direction: WindowDirection, window: CGRect, screen: CGRect, screens: [CGRect]) -> CGRect? {
        let target: CGRect? = switch direction {
        case .nextScreen: ScreenUtility.next(from: screen, in: screens, frame: { $0 })
        case .previousScreen: ScreenUtility.previous(from: screen, in: screens, frame: { $0 })
        default: nil
        }

        guard let target else { return nil }
        return WindowFrameResolver.getFrame(
            for: proportionalAction(window: window, bounds: screen),
            bounds: target,
            padding: .zero
        )
    }
}
